export type IQuote = {
    text: string;
    author: string;
};

export const quotes = [
    { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { text: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", author: "Albert Einstein" },
    { text: "So many books, so little time.", author: "Frank Zappa" },
    { text: "A room without books is like a body without a soul.", author: "Marcus Tullius Cicero" },
    { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
    { text: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain" },
    { text: "Without music, life would be a mistake.", author: "Friedrich Nietzsche" },
    { text: "We accept the love we think we deserve.", author: "Stephen Chbosky" },
    { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
    { text: "It is never too late to be what you might have been.", author: "George Eliot" },
    { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
    { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
    { text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
    { text: "If you judge people, you have no time to love them.", author: "Mother Teresa" },
    { text: "Everything has beauty, but not everyone sees it.", author: "Confucius" },
    { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
    { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison" },
    { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
    { text: "Life isn't about finding yourself. It's about creating yourself.", author: "George Bernard Shaw" },
    { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
    { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
    { text: "An unexamined life is not worth living.", author: "Socrates" },
    { text: "Don't cry because it's over, smile because it happened.", author: "Dr. Seuss" },
    { text: "Life is what happens to us while we are making other plans.", author: "Allen Saunders" },
    { text: "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.", author: "Marilyn Monroe" },
    { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
    { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
    { text: "We must not allow other people’s limited perceptions to define us.", author: "Virginia Satir" },
    { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
    { text: "Whether you think you can or you think you can’t, you’re right.", author: "Henry Ford" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "The best way out is always through.", author: "Robert Frost" },
    { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { text: "Change the world by being yourself.", author: "Amy Poehler" },
    { text: "Every moment is a fresh beginning.", author: "T.S. Eliot" },
    { text: "Die with memories, not dreams.", author: "Unknown" },
    { text: "Aspire to inspire before we expire.", author: "Unknown" },
    { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Do what you feel in your heart to be right – for you’ll be criticized anyway.", author: "Eleanor Roosevelt" },
    { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
    { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen R. Covey" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
] satisfies IQuote[];
